version: '2'

services:
   Tito-SQL:
     container_name: tito-sql
     image: vmeoc/tito-sql:V1.5
     volumes:
       - "./data/db:/var/lib/mysql"
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: Tito2016
       MYSQL_USER: root
       MYSQL_PASSWORD: Tito2016

   Tito-FE:
     depends_on:
       - Tito-SQL
     image: vmeoc/tito-fe:V1.5.1
     links:
       - Tito-SQL
     ports:
       - "80:80"
     restart: always     