version: '2'
services:
  Tito-FE:
    image: vmeoc/tito-fe:V1.7.1.1
    ports:
      - 80
    networks:
      - front-tier
      - back-tier
    restart: always
    links:
        - Tito-SQL

  Tito-SQL:
    image: vmeoc/tito-sql:V1.5
    links:
      - Tito-FE
    networks:
      - back-tier
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Tito2016
#removed until automated volume deployment is available
#    volumes:
#      - "./data/db:/var/lib/mysql"

 
networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
