apiVersion: v1
kind: Pod
metadata:
  generateName: titosql-
  labels:
    name: tito-sql
    version: "1.5"
    app: tito
    stage: prod
    tiers: tito-sql
spec:
  containers:
    - name: tito-sql
      image: vmeoc/tito-sql:V1.5
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 3306
      env:
      - name: MYSQL_ROOT_PASSWORD
        value: Tito2016
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace

---

apiVersion: v1
kind: Service
metadata:
  name: tito-sql-service
  labels:
    app: tito
    tiers: tito-sql
    stage: prod
spec:
  ports:
      - port: 3306               # port expose par docker  (pas le port dans le container)
  selector:                     # key/value, label permettant de definir le pod cible (doit etre danslabels du pod)
    tiers: tito-sql


---

apiVersion: v1
kind: ReplicationController
metadata:
  name: titofe
  labels:
    name: tito-fe
    version: "latest"
    app: tito
    tiers: tito-fe
    stage: prod
spec:
  replicas: 2
  selector:
    type: tito-fe
    version: v1
  template:
    metadata:
      labels:
        app: tito
        type: tito-fe
        version: v1
    spec:
      containers:
        - name: tito
          image: vmeoc/tito-fe:V1.9.4
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 80
          env:
          - name: TITO_VERSION
            value: V1.9.6
          - name: TITO_SQL_SERVICE_HOST
            value: tito-sql
          - name: PROXY_NAME
            value: wavefront-proxy.corp.local
          - name: PROXY_PORT
            value: "2878"
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace

---

apiVersion: v1
kind: Service
metadata:
  name: titofe-service
  labels:
    app: tito
    stage: prod
spec:
  ports:
  - name: http
    port: 80               # port expose par docker  (pas le port dans le container)
  selector:                # key/value, label permettant de definir le pod cible (doit etre danslabels du pod)
    type: tito-fe
  type: LoadBalancer







